version: '3.7'

services:
  archvr-mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: archvr-mssql
    ports: 
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      # MSSQL_DB: mydb
      # MSSQL_USER: myuser
      # MSSQL_PASSWORD: Mypass123

    # networks:
    #   - backend
    volumes:
        - ~/sql-server:/var/opt/mssql/data